In [4]:
import numpy as np

In [13]:
arr1 = np.arange(1,5)
arr2 = np.arange(5,9)

In [17]:
arr1 = arr1.reshape(2,2)
arr2 = arr2.reshape(2,2)

In [22]:
print(arr1,end="\n\n")
print(arr2)

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]


In [18]:
arr = arr1.dot(arr2)
print(arr)

[[19 22]
 [43 50]]
