In [1]:
import numpy as np

In [17]:
arr1 = np.array([1,2,3,4,5,6,7,8,9])
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
np.random.seed(23)
arr2 = np.random.randint(0,10,10)
arr2

array([3, 6, 8, 9, 6, 8, 7, 9, 3, 6])

In [24]:
arr3 = np.arange(10,21)
arr3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [28]:
arr4 = np.full(10,5)
arr4

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [39]:
np.random.seed(12)
arr5 = np.random.randint(0,10,9).reshape((3,3))
arr5

array([[6, 1, 2],
       [3, 3, 0],
       [6, 1, 4]])

In [71]:
arr5.cumsum(axis=1)

array([[ 6,  7,  9],
       [ 3,  6,  6],
       [ 6,  7, 11]], dtype=int32)

In [73]:
np.random.seed(12)
arr6 = np.arange(1,10).reshape((3,3))
arr6[arr6%2 == 0] = 0
arr6

array([[1, 0, 3],
       [0, 5, 0],
       [7, 0, 9]])

In [46]:
arr7 = np.random.rand(9).reshape((3,3))
arr7

array([[0.21764164, 0.98656115, 0.17284219],
       [0.1216038 , 0.5454636 , 0.42172443],
       [0.60825806, 0.78942648, 0.92674104]])

In [74]:
import random as r
r.randint(0,9)

5

In [77]:
arr9 = np.arange(1,17).reshape((4,4))
arr9

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [82]:
arr9[1:,1:3]

array([[ 6,  7],
       [10, 11],
       [14, 15]])

In [96]:
arr10 = np.arange(1,11)
arr11 = np.arange(11,21)
np.hstack((arr10, arr11))
# np.vstack((arr10, arr11))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [98]:
%timeit 2+3

10.6 ns ± 1.66 ns per loop (mean ± std. dev. of 7 runs, 100000000 loops each)


In [101]:
%timeit [i**2 for i in range(1,11)]

3.12 µs ± 59.6 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [102]:
%timeit [np.arange(1,11)**2]

1.46 µs ± 280 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
